spring.application.name=autoservice-backend

# local progresql 
# spring.datasource.url=jdbc:postgresql://localhost:5432/auto_service
# spring.datasource.username=postgres
# spring.datasource.password=
# spring.datasource.driver-class-name=org.postgresql.Driver


#Host PostgresSQL database configuration
spring.datasource.url=jdbc:postgresql://auto-service-db-server.postgres.database.azure.com:5432/auto-service
spring.datasource.username=test
spring.datasource.password=test@1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# JWT config    
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong
jwt.expiration=86400

#Email configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3c9dc3f073efec
spring.mail.password=636cfb51c7e332
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

